name: docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.6]
        
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Checkout 🛎️
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
          python3.6 -m pip install -U sphinx
          python3.6 -m pip install sphinx-rtd-theme
          
      - name: Build Docs
        run: |
          sphinx-build -b html ./doc/source/ public
          touch public/.nojekyll
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public